first build yaml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,40 +1,29 @@
-# Name of the workflow. This will appear in the GitHub Actions UI.
 name: Build Solution
 
-# Trigger for the workflow. This workflow is triggered manually using the `workflow_dispatch` event.
 on:
   workflow_dispatch:
 
-# Environment variables used throughout the workflow.
-# These are sensitive values stored in GitHub Secrets and injected at runtime.
 env:
-    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}  # AWS access key for authentication.
-    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # AWS secret key for authentication.
-    AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}  # Default AWS region for resource deployment.
+    ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
+    ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
+    ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
+    ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
 
-# Jobs define the sequence of tasks to be executed in the workflow.
 jobs:
-  # First job: Builds an Amazon Elastic Container Registry (ECR) instance.
   deploy_phase_1:
-    name: Build ECR Instance  # Human-readable name for the job.
-    runs-on: ubuntu-latest  # Specifies the runner environment (Ubuntu latest).
+    name: Build ACR Instance
+    runs-on: ubuntu-latest
     steps:
-      # Step 1: Checkout the repository code to the runner.
       - name: Checkout Code
-        uses: actions/checkout@v3  # Uses the official GitHub Actions checkout action.
+        uses: actions/checkout@v3
 
-      # Step 2: Set up Terraform on the runner.
       - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2  # Uses the official HashiCorp Terraform setup action.
+        uses: hashicorp/setup-terraform@v2
 
-      # Step 3: Apply Terraform to create the ECR instance.
       - name: Apply Terraform
         run: |
-          # Navigate to the directory containing the Terraform configuration for ECR.
-          cd "01-ecr" 
-          echo "NOTE: Building ECR Instance."
-
-          # Prevent a mess from happening if you run the github action without a backend
+          cd "01-acr"
+          echo "NOTE: Building ACR Instance."
 
           backend=$(grep -r 'backend ' *.tf || true)
           if [ -z "$backend" ]; then
@@ -42,74 +31,52 @@ jobs:
               exit 1
           fi
 
-          # Initialize Terraform in the directory.
           terraform init
-
-          # Apply the Terraform configuration to create the ECR instance.
-          # The `-auto-approve` flag skips manual confirmation.
           terraform apply -auto-approve
-
-          # Navigate back to the root directory.
           cd ..
 
-  # Second job: Builds a Docker container for the Flask application and pushes it to ECR.
   deploy_phase_2:
-    name: Build Flask Container  # Human-readable name for the job.
-    needs: deploy_phase_1  # Ensures this job runs only after `deploy_phase_1` completes.
-    runs-on: ubuntu-latest  # Specifies the runner environment (Ubuntu latest).
+    name: Build Flask Container
+    needs: deploy_phase_1
+    runs-on: ubuntu-latest
     steps:
-      # Step 1: Checkout the repository code to the runner.
       - name: Checkout Code
-        uses: actions/checkout@v3  # Uses the official GitHub Actions checkout action.
+        uses: actions/checkout@v3
 
-      # Step 2: Set up Docker Buildx for building and pushing Docker images.
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v2  # Uses the official Docker Buildx setup action.
+        uses: docker/setup-buildx-action@v2
         with:
-            install: true  # Ensures Docker Buildx is installed.
+            install: true
 
-      # Step 3: Build the Flask container and push it to the ECR instance.
       - name: Build Flask Container
         run: |
-            # Navigate to the directory containing the Docker configuration.
-            cd "02-docker"
-            echo "NOTE: Building flask container with Docker."
+          cd "02-docker"
+          echo "NOTE: Building flask container with Docker."
 
-            # Retrieve the AWS Account ID using the AWS CLI.
-            AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
+          RESOURCE_GROUP="flask-container-rg"
+          ACR_NAME=$(az acr list --resource-group $RESOURCE_GROUP --query "[?starts_with(name, 'flaskapp')].name | [0]" --output tsv)
+          az acr login --name $ACR_NAME
+          ACR_REPOSITORY="${ACR_NAME}.azurecr.io/flask-app"
+          IMAGE_TAG="flask-app-rc1"
+          docker build -t ${ACR_REPOSITORY}:${IMAGE_TAG} . --push
 
-            # Authenticate Docker to the AWS ECR registry using the retrieved credentials.
-            aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com
+          cd ..
 
-            # Build the Docker image and push it to the ECR repository.
-            # The image tag includes the AWS Account ID, repository name, and a specific tag (`flask-app-rc1`).
-            docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-2.amazonaws.com/flask-app:flask-app-rc1 . --push
-
-            # Navigate back to the root directory.
-            cd ..
-
-  # Third job: Builds an AWS App Runner instance and deploys the Flask container.
   deploy_phase_3:
-    name: Build App Runner Instance  # Human-readable name for the job.
-    needs: deploy_phase_2  # Ensures this job runs only after `deploy_phase_2` completes.
-    runs-on: ubuntu-latest  # Specifies the runner environment (Ubuntu latest).
+    name: Build Container App
+    needs: deploy_phase_2
+    runs-on: ubuntu-latest
     steps:
-      # Step 1: Checkout the repository code to the runner.
       - name: Checkout Code
-        uses: actions/checkout@v3  # Uses the official GitHub Actions checkout action.
+        uses: actions/checkout@v3
 
-      # Step 2: Set up Terraform on the runner.
       - name: Setup Terraform
-        uses: hashicorp/setup-terraform@v2  # Uses the official HashiCorp Terraform setup action.
+        uses: hashicorp/setup-terraform@v2
 
-      # Step 3: Apply Terraform to create the App Runner instance.
       - name: Apply Terraform
         run: |
-            # Navigate to the directory containing the Terraform configuration for App Runner.
-            cd 03-apprunner
-            echo "NOTE: Building apprunner instance and deploy flask container."
-
-            # Prevent a mess from happening if you run the github action without a backend
+            cd 03-containerapp
+            echo "NOTE: Building container app instance and deploy flask container."
 
             backend=$(grep -r 'backend ' *.tf || true)
             if [ -z "$backend" ]; then
@@ -117,46 +84,50 @@ jobs:
               exit 1
             fi
 
-            # Initialize Terraform in the directory.
             terraform init
-
-            # Apply the Terraform configuration to create the App Runner instance.
-            # The `-auto-approve` flag skips manual confirmation.
             terraform apply -auto-approve
-
-            # Navigate back to the root directory.
             cd ..
 
-  # Fourth job: Validates the deployed solution by testing the App Runner service.
   validate:
-    name: Validate Solution  # Human-readable name for the job.
-    needs: deploy_phase_3  # Ensures this job runs only after `deploy_phase_3` completes.
-    runs-on: ubuntu-latest  # Specifies the runner environment (Ubuntu latest).
+    name: Validate Solution
+    needs: deploy_phase_3
+    runs-on: ubuntu-latest
     steps:
-      # Step 1: Checkout the repository code to the runner.
       - name: Checkout Code
-        uses: actions/checkout@v3  # Uses the official GitHub Actions checkout action.
+        uses: actions/checkout@v3
 
-      # Step 2: Validate the deployed App Runner service.
       - name: Validate Solution
         run: |
-            # Fetch the default domain of the App Runner service.
-            SERVICE_NAME="flask-app-runner"
-            SERVICE_URL=$(aws apprunner list-services --query "ServiceSummaryList[?ServiceName=='$SERVICE_NAME'].ServiceUrl" --output text)
+          CONTAINER_APP="flask-container-app"
+          RESOURCE_GROUP="flask-container-rg"
 
-            # Check if the SERVICE_URL is empty or invalid.
-            if [[ -z "$SERVICE_URL" || "$SERVICE_URL" == "None" ]]; then
-                echo "ERROR: Default domain for App Runner service '$SERVICE_NAME' could not be retrieved. Please check if the service exists and try again."
-                exit 1  # Exit with an error code if the service URL is invalid.
+          # Get the service URL
+          SERVICE_URL=$(az containerapp show --name "$CONTAINER_APP" --resource-group "$RESOURCE_GROUP" --query "properties.configuration.ingress.fqdn" --output tsv)
+
+          # Check if the SERVICE_URL is empty
+          if [[ -z "$SERVICE_URL" || "$SERVICE_URL" == "None" ]]; then
+              echo "ERROR: Service URL for $CONTAINER_APP is not found. Please check if the service exists and try again."
+              exit 1
+          fi
+
+          # Wait for ingress to be ready
+          echo "NOTE: Waiting for the API to be reachable..."
+
+          while true; do
+            HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://$SERVICE_URL/candidate/John%20Smith")
+
+            if [[ "$HTTP_STATUS" == "200" ]]; then
+                echo "NOTE: API is now reachable."
+                break
+            else
+                echo "WARNING: API is not yet reachable (HTTP $HTTP_STATUS). Retrying..."
+                sleep 30
             fi
+          done
 
-            # Navigate to the directory containing the test script.
-            cd ./02-docker
-
-            # Construct the full URL for the App Runner service.
-            SERVICE_URL="https://$SERVICE_URL"
-            echo "NOTE: Testing the App Runner Solution."
-            echo "NOTE: URL for App Runner Solution is $SERVICE_URL/gtg?details=true"
-
-            # Run the test script to validate the App Runner service.
-            ./test_candidates.py $SERVICE_URL
+          # Move to the directory and run the test script
+          cd ./02-docker
+          SERVICE_URL="https://$SERVICE_URL"
+          echo "NOTE: Testing the Azure Container App Solution."        
+          echo "NOTE: URL for Azure Container App is $SERVICE_URL/gtg?details=true"
+          ./test_candidates.py "$SERVICE_URL"
