add role check to checkenv.yml

diff --git a/.github/workflows/checkenv.yml b/.github/workflows/checkenv.yml
--- a/.github/workflows/checkenv.yml
+++ b/.github/workflows/checkenv.yml
@@ -143,3 +143,21 @@ jobs:
 
             # Inform the user that all required backend files exist.
             echo "NOTE: All required backend files exist."
+
+            # Get the current user or service principal
+            ASSIGNEE=$(az account show --query user.name -o tsv)
+
+            if [ -z "$ASSIGNEE" ]; then
+                echo "ERROR: Unable to retrieve the logged-in user or service principal."
+                exit 1
+            fi
+
+            # Check for the 'User Access Administrator' role
+            ROLE_CHECK=$(az role assignment list --assignee "$ASSIGNEE" --query "[?roleDefinitionName=='User Access Administrator']" -o tsv)
+
+            if [ -z "$ROLE_CHECK" ]; then
+              echo "ERROR: 'User Access Administrator' role is NOT assigned to current service principal."
+              exit 1
+            else
+              echo "NOTE: 'User Access Administrator' role is assigned to current service principal."
+            fi
